# Generated by Django 3.2 on 2021-05-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profesores_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesores',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='profesores',
            name='nombre',
        ),
        migrations.AddField(
            model_name='profesores',
            name='apellidos',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profesores',
            name='catedra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profesores',
            name='contraseña',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profesores',
            name='nombres',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profesores',
            name='correo',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
