# Generated by Django 3.2 on 2021-05-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210508_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesores',
            name='apellidos',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profesores',
            name='contraseña',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profesores',
            name='correo',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profesores',
            name='nombres',
            field=models.CharField(max_length=100),
        ),
    ]
