# Generated by Django 3.2 on 2021-05-09 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210508_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesores',
            name='catedra',
        ),
        migrations.RemoveField(
            model_name='profesores',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='profesores',
            name='correo',
        ),
        migrations.AlterField(
            model_name='profesores',
            name='nombres',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
