# Generated by Django 3.2 on 2021-05-09 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210508_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesores',
            name='catedra',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profesores',
            name='contraseña',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profesores',
            name='correo',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profesores',
            name='apellidos',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profesores',
            name='nombres',
            field=models.CharField(default='', max_length=100),
        ),
    ]
