# Generated by Django 3.2 on 2021-05-09 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_estudiantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='', max_length=100)),
                ('asignatura', models.CharField(default='', max_length=100)),
                ('semestre', models.CharField(default='', max_length=100)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profesor', to='app.profesores')),
            ],
        ),
    ]
