# Generated by Django 3.2 on 2021-05-11 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210511_1800'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estudiantes',
        ),
        migrations.DeleteModel(
            name='Grupos',
        ),
        migrations.DeleteModel(
            name='profesores',
        ),
    ]
