# Generated by Django 3.2 on 2021-05-11 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0012_auto_20210511_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('catedra', models.BooleanField(default=False)),
            ],
        ),
    ]
