# Generated by Django 3.2 on 2021-05-18 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_profesores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigogrupo', models.CharField(max_length=50)),
                ('asignatura', models.CharField(max_length=50)),
                ('semestre', models.CharField(max_length=50)),
                ('profesorgrupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profesorgrupo', to='app.profesores')),
            ],
        ),
    ]
