# Generated by Django 3.2 on 2021-05-18 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_grupos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupos',
            old_name='codigogrupo',
            new_name='codigo',
        ),
        migrations.RemoveField(
            model_name='grupos',
            name='profesorgrupo',
        ),
        migrations.AddField(
            model_name='grupos',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grupo', to='app.profesores'),
        ),
    ]
