# Generated by Django 3.2 on 2021-06-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_actividad_estudiantegrupo_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='valor',
            field=models.FloatField(default=0),
        ),
    ]
